### ISSUE TITLE
Exception from Jurassic

### ISSUE THREAD

**Issue by suhrab** [darcythomas/zxcvbn.net#4]
**Breaks on this line**:
https://github.com/darcythomas/zxcvbn.net/blob/master/zxcvbn.net/ZxcvbnInstance.cs#L33

**The exception itself**:
Jurassic.JavaScriptException was unhandled by user code
  HResult=-2146233088
  Message=Error: **Maximum number of named properties reached.**
  Source=Jurassic
  LineNumber=0
  Name=Error
  StackTrace:
       at Jurassic.Library.ObjectInstance.AddProperty(String propertyName, Object value, PropertyAttributes attributes, Boolean throwOnError)
       at Jurassic.Library.ObjectInstance.SetPropertyValue(String propertyName, Object value, Boolean throwOnError)
       at anonymous(ScriptEngine , Scope , Object , FunctionInstance , Object[] )
       at Jurassic.Library.UserDefinedFunction.CallLateBound(Object thisObject, Object[] argumentValues)
       at Jurassic.Library.FunctionInstance.CallWithStackTrace(String path, String function, Int32 line, Object thisObject, Object[] argumentValues)
       at anonymous(ScriptEngine , Scope , Object , FunctionInstance , Object[] )
       at Jurassic.Library.UserDefinedFunction.CallLateBound(Object thisObject, Object[] argumentValues)
       at Jurassic.Library.FunctionInstance.CallWithStackTrace(String path, String function, Int32 line, Object thisObject, Object[] argumentValues)
       at global_(ScriptEngine , Scope , Object )
       at Jurassic.Compiler.GlobalMethodGenerator.Execute()
       at Jurassic.ScriptEngine.Execute(ScriptSource source)
       at Jurassic.ScriptEngine.Execute(String code)
       at zxcvbn.net.ZxcvbnInstance.ScriptEngine() in d:\publicGitRepos\zxcvbn.net\zxcvbn.net\ZxcvbnInstance.cs:line 33
       at System.Lazy`1.CreateValue()
  InnerException: 

**Jurassic exception comes from here**
https://github.com/Alxandr/Jurassic/blob/master/Jurassic/Library/Object/ObjectInstance.cs#L881

**Comment by darcythomas** [comment]
Thanks for that @suhrab 

I will put this in my backlog to resolve on the weekend.

Can you give me details of the machine you are running this code on:
- OS
- 32 or 64 bit
- What version of .Net
-  Amount of ram

**Comment by suhrab** [comment]
Windows 8.1 Enterprise
x64
dotnet 4.5.1
8GB

**Comment by darcythomas** [comment]
@suhrab FYI I have changed the js engine to V8 so that should not be able to handle things better.

When you get a chance can you try the latest nuget package and see if it is playing nicely for you now.

Cheers,

Darcy
